language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
  - pip list
script:
  - dir
  - coverage run --source=verticalDotLeaves tests/test_VerticalDotLeaves.py
after_success:
  - coveralls

